version: '2'
services:
        guacd:
            image: guacamole/guacd
        guac-serve:
            image: guacamole/guacamole
            links:
                - guacd:guacd
                - mysql:mysql
            ports:
                - 7999:8080
            environment:
                - MYSQL_HOSTNAME=mysql
                - MYSQL_DATABASE=guacamole
                - MYSQL_USER=guacamole
                - MYSQL_PASSWORD=guacamole
                - GUACD_HOSTNAME=guacd
                - GUACD_PORT=4822
        mysql:
            image: mysql
            environment: 
                - MYSQL_ROOT_PASSWORD=guacamole
                - MYSQL_DATABASE=guacamole
                - MYSQL_USER=guacamole
                - MYSQL_PASSWORD=guacamole
            volumes:
                - data:/var/lib/mysql
volumes:
        data: